### ISSUE TITLE
Getting Rate Limited

### ISSUE THREAD

**Issue by hoemotion** [logicguy1/Mass-Dm-Self-Bot#9]
I have logged about 14k ids.. i added a 3 secs sleep to the send messages part, but im still getting rate limited after like 40 dms, i even put a 60 secs sleep, if i get rate limited, but im still getting rate limited. Could you add a working rate limits handler?
I think it would work with proxies but idk how to manage that by myself

**Comment by Mikquaj** [comment]
time.sleep()

**Comment by hoemotion** [comment]
> time.sleep()

await asyncio.sleep() is quite better lol, i was a newby at python back then when i opened this issue
